version: 2

sources:
  - name: public_exercises
    schema: public_exercises
    tables:
      - name: users
        description: "Information about the users of the system."
        columns:
          - name: id
            description: "Unique identifier for each user."

          - name: email
            description: "Email address of the user."
            tests:
              - not_null:
                  name: "`users.email` doesn't contain NULL."
              - unique:
                  name: "`users.email` values are unique."

          - name: created_at
            description: "Timestamp indicating when the user account was created."
            tests:
              - not_null:
                  name: "`users.created_at` doesn't contain NULL."


      - name: orders
        description: "Information about each order placed by users."
        columns:
          - name: id
            description: "Unique identifier for each order."
            tests:
              - unique:
                  name: "`orders.id` values are unique."
          - name: user_id
            description: "Identifier for the user who placed the order. This is a FK referencing the `id` in the `users` table."

          - name: amount
            description: "Total monetary value of the order."
            tests:
              - not_null:
                  name: "`orders.amount` doesn't contain NULL."
              - dbt_utils.expression_is_true:
                  expression: "<= 0"
                  name: "`orders.amount` not less or equal to 0."

          - name: created_at
            description: "Timestamp indicating when the order was created."
            tests:
              - not_null:
                  name: "`orders.created_at` doesn't contain NULL."

          - name: shipped_at
            description: "Timestamp indicating when the order was shipped."
            tests:
              - dbt_utils.expression_is_true:
                  expression: "> created_at"
                  name: "`orders` shipped_at > created_at"


      - name: events
        description: "Logs of various events associated with users."
        columns:
          - name: id
            description: "Unique identifier for each event."
            tests:
              - unique:
                  name: "`events.id` values are unique."
          - name: user_id
            description: "Identifier for the user associated with the event. This is a FK referencing the `id` in the `users` table."

          - name: event_name
            description: "Name of the event."
            tests:
              - accepted_values:
                  values: ['Sign Up', 'Purchase', 'Order shipped', 'AdvertisingCampaignSet']
                  name: "`events.event_name` values validation."

          - name: created_at
            description: "Timestamp indicating when the event occurred."
            tests:
              - not_null:
                  name: "`events.created_at` doesn't contain NULL."

          - name: params
            description: "Additional parameters or data related to the event."
